export const months = [
    [ /* MÊS COR
        0 - 'Nome do mês',
        1 - 'Doença',
        2 - 'Definição',
        3 - 'Estatísticas',
        4 - 'O que Aumenta o Risco',
        5 - 'Como Prevenir',
        6 - 'Sinais e Sintomas',
        7 - 'Detecção Precoce',
        8 - 'Diagnóstico',
        9 - 'Tratamento',*/
    ],
    [ // JANEIRO BRANCO
        'Janeiro Branco',
        'Prevenção às Doenças Mentais',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // FEVEREIRO ROXO
        'Fevereiro Roxo',
        'Prevenção ao Alzheimer',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // MARÇO LILÁS
        'Março Lilás',
        'Prevenção ao Câncer de Colo de Útero',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // ABRIL AZUL
        'Abril Azul',
        'Conscientização sobre o Autismo',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // MAIO VERMELHO
        'Maio Vermelho',
        'Prevenção às Hepatites',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // JUNHO LARANJA
        'Junho Laranja',
        'Prevenção à Leucemia',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // JULHO AMARELO
        'Julho Amarelo',
        'Prevenção ao Câncer Ósseo',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // AGOSTO LARANJA
        'Agosto Laranja',
        'Prevenção à Esclerose Múltipla',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // SETEMBRO AMARELO
        'Setembro Amarelo',
        'Prevenção ao Suicídio',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // OUTUBRO ROSA
        'Outubro Rosa',
        'Prevenção ao Câncer de Mama',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // NOVEMBRO AZUL
        'Novembro Azul',
        'Prevenção ao Câncer de Próstata',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // DEZEMBRO VERMELHO
        'Dezembro Vermelho',
        'Prevenção à AIDS',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ]
]