export const months = [
    /*
    [ // MÊS COR
        0 - 'Nome do mês',
        1 - 'Doença',
        2 - 'Definição',
        3 - 'Estatísticas',
        4 - 'O que Aumenta o Risco',
        5 - 'Como Prevenir',
        6 - 'Sinais e Sintomas',
        7 - 'Detecção Precoce',
        8 - 'Diagnóstico',
        9 - 'Tratamento',
    ]
    */

    [ // JANEIRO BRANCO
        'Janeiro Branco',
        'Prevenção às Doenças Mentais',
        'Saúde mental refere-se a um bem estar no qual o indivíduo desenvolve suas habilidades pessoais, consegue lidar com os estresses da vida, trabalha de forma produtiva e encontra-se apto a dar sua contribuição para sua comunidade. Este mês é dedicado à conscientização acerca da saúde mental e à prevenção de doenças mentais, como a ansiedade e a depressão.',
        'De acordo com estudos da Organização Mundial da Saúde (OMS) e da Organização Pan-americana da Saúde (OPAS), o Brasil é o país mais ansioso do mundo (9,3%) e o segundo maior das Américas em depressão (5,8%). ',
        'Para a ansiedade: \n - Genética \n - Evento traumático \n- Situações estressantes \n - Doenças físicas \n - Distúrbios hormonais \n - Traumas de infância \n\n Para a depressão:',
        '- Checapes por exames neurológicos \n - Avaliações psicológicas regulares \n - Conhecimento do histórico genético \n - Evitar situações de estresse \n - Manter hábitos saudáveis de alimentação e esporte',
        'Para a ansiedade: \n- Reações físicas: taquicardia (aumento dos batimentos cardíacos), hipertensão (tensão alta), contração gástrica (sensação de nó no estômago), dificuldades respiratórias (falta de ar), boca seca, sudorese (transpiração excessiva), náuseas ou vómitos, diarreia, dor de cabeça, dores nas costas, sensação de aumento de temperatura (hipertermia ou “febre emocional”), alopécia (queda de cabelo), perda ou aumento de apetite, perda ou aumento de peso, alterações no ciclo menstrual, unhas quebradiças, etc; \n- Reações comportamentais: tremores, bloqueio ou paralisação, estado de alerta, irritabilidade, tensão nos maxilares, alterações do tom de voz, hiperatividade motora (ex: caminhar de um lado para o outro), roer as unhas...; \n- Reações cognitivas (alterações no modo como processa a informação): preocupação excessiva/obsessiva, pensamentos intrusivos negativos, dificuldades de atenção e concentração, insónias (perturbações de sono, como dificuldades em adormecer ou acordar várias vezes durante a noite), alterações de memória, vontade de chorar; maior foco no negativo do que no positivo (pessimismo generalizado)...; \n- Reações sociais: dificuldades em iniciar ou manter uma conversa, dificuldade em dizer “não” ou em demonstrar desacordo/desagrado, preocupação excessiva com a opinião de terceiros, evitamento ou tentativa de passar constantemente despercebido/a... \n\n Para a depressão: \n- Humor deprimido, que se caracteriza por desânimo persistente, baixa autoestima, sentimentos de inutilidade; \n- Perda de interesse em atividades que antes a pessoa apreciava; \n- Mudança de apetite, ganho ou perda de peso; \n- Perda de energia ou fadiga acentuada; \n- Movimentos físicos sem sentido, como apertar as mãos de forma constante e nervosa; \n- Sentir-se sem esperança e culpado; \n- Dificuldades para raciocinar, se concentrar ou tomar decisões; \n- Pensamentos de morte ou suicídio; \n- Irritabilidade, ansiedade e angústia; \n- Necessidade de um grande esforço para fazer coisas que antes eram fáceis; \n- Diminuição ou incapacidade de sentir alegria; \n- Sentimentos de medo, insegurança, desespero, desamparo e vazio; \n- Interpretação distorcida e negativa da realidade; \n- Diminuição do desejo e do desempenho sexual; \n- Dores e outros sintomas físicos sem uma causa aparente, como dores de barriga, azia, má digestão, diarréia, prisão de ventre, gases, tensão na nuca e nos ombros, dor de cabeça ou no corpo, sensação de corpo pesado ou de pressão no peito.',
        'A detecção de transtornos mentais se dá, principalmente, pelo aparecimento de sintomas. Por isso, é importante atentar-se à presença de possíveis indicadores de doenças mentais.',
        'O diagnóstico da ansiedade é realizado pela análise clínica com um médico psiquiatra, o qual verificará os sintomas apresentados pelo paciente. \nEfeitos colaterais de medicamentos e outras doenças podem provocar sinais parecidos com os da depressão, o que também complica o diagnóstico. \nUma pessoa que apresenta esses sinais deve, primeiro, fazer exames clínicos para verificar se sofre de alguma doença. Se estiver tomando algum medicamento, deve consultar um médico para avaliar quais efeitos essa substância está provocando em seu organismo. \nO diagnóstico da depressão é feito a partir da presença de, pelo menos, dois sintomas.',
        'O tratamento da ansiedade consiste, principalmente, em psicoterapia, sendo que, em alguns casos, a administração de medicamentos pode ser recomendada. \nA depressão é um transtorno que pode ser amenizado e seus sintomas podem até desaparecer dependendo do tratamento empregado. \nEsse tratamento é feito com medicamentos antidepressivos e psicoterapia. A internação do paciente pode ser recomendada quando ele apresenta um perigo à própria saúde ou às pessoas de seu convívio. \nTratar a depressão não é simples e cada paciente pode apresentar uma evolução diferente, dependendo da forma como seu organismo reage.',
    ],
    [ // FEVEREIRO ROXO
        'Fevereiro Roxo',
        'Prevenção ao Alzheimer',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // MARÇO LILÁS
        'Março Lilás',
        'Prevenção ao Câncer de Colo de Útero',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // ABRIL AZUL
        'Abril Azul',
        'Conscientização sobre o Autismo',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // MAIO VERMELHO
        'Maio Vermelho',
        'Prevenção às Hepatites',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // JUNHO LARANJA
        'Junho Laranja',
        'Prevenção à Leucemia',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // JULHO AMARELO
        'Julho Amarelo',
        'Prevenção ao Câncer Ósseo',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // AGOSTO LARANJA
        'Agosto Laranja',
        'Prevenção à Esclerose Múltipla',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // SETEMBRO AMARELO
        'Setembro Amarelo',
        'Prevenção ao Suicídio',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // OUTUBRO ROSA
        'Outubro Rosa',
        'Prevenção ao Câncer de Mama',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // NOVEMBRO AZUL
        'Novembro Azul',
        'Prevenção ao Câncer de Próstata',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // DEZEMBRO VERMELHO
        'Dezembro Vermelho',
        'Prevenção à AIDS',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ]
]