export const months = [
    [ /* MÊS COR
        0 - 'Nome do mês',
        1 - 'Doença',
        2 - 'Definição',
        3 - 'Estatísticas',
        4 - 'O que Aumenta o Risco',
        5 - 'Como Prevenir',
        6 - 'Sinais e Sintomas',
        7 - 'Detecção Precoce',
        8 - 'Diagnóstico',
        9 - 'Tratamento',*/
    ],
    [ // JANEIRO BRANCO
        'Janeiro Branco',
        'Prevenção às Doenças Mentais',
        'A saúde mental refere-se a um bem estar onde o indivíduo consegue lidar com os estresses da vida e consegue contribuir para sua comunidade. Este mês é dedicado à prevenção de doenças mentais, como a ansiedade e a depressão.',
        'De acordo com estudos da Organização Mundial da Saúde (OMS) e da Organização Pan-americana da Saúde (OPAS), o Brasil é o país mais ansioso do mundo (9,3%) e o segundo maior das Américas em depressão (5,8%).',
        'Para a ansiedade pode-se listar a genética, um evento traumático e situações estressantes geradas por expectativa. Para a depressão a presença de histórico familiar, um estresse crônico, traumas psicológicos ou mudança brusca de condições financeiras e desemprego.',
        'Com checapes por exames neurológicos, avaliações psicológicas regulares, conhecimento do histórico genético, evitar situações de estresse e manter hábitos saudáveis de alimentação e esporte.',
        '',
        'A detecção de transtornos mentais se dá, principalmente, pelo aparecimento de sintomas. Por isso, é importante atentar-se à presença de possíveis indicadores de doenças mentais.',
        'O diagnóstico da ansiedade é realizado pela análise clínica com um médico psiquiatra, o qual verificará os sintomas apresentados pelo paciente. Se estiver tomando algum medicamento, deve consultar um médico para avaliar quais efeitos essa substância está provocando em seu organismo.',
        'O tratamento de doenças mentais como a depressão e ansiedade não é simples e cada paciente pode apresentar uma evolução diferente. Ela consiste, principalmente, em psicoterapia, sendo que, em alguns casos, a administração de medicamentos antidepressivos pode ser recomendada. A internação do paciente pode ser recomendada quando ele apresenta um perigo à própria saúde ou às pessoas de seu convívio.',
    ],
    [ // FEVEREIRO ROXO
        'Fevereiro Roxo',
        'Prevenção ao Alzheimer',
        'A doença de Alzheimer é a forma mais comum da demência no mundo inteiro e é uma desordem neurodegenerativa progressiva. A causa é desconhecida, mas acredita-se que seja geneticamente determinada.',
        'Considerado a forma mais comum de demência, é responsável por 60% a 70% dos casos. A estimativa é de que, no mundo inteiro, 47 milhões de pessoas sofram de demência e, a cada ano, cerca de 10 milhões de novos casos sejam registrados.',
        'A Doença de Alzheimer se desenvolve a partir de múltiplos fatores identificados por cientistas, dentre eles destacam-se a idade, a genética, ocorrência de algum traumatismo craniano, depressão, estilo de vida e ambiente.',
        'Praticar atividade física, comer de forma equilibrada e manter a mente sempre funcionando são medidas capazes de afastar (ou pelo menos retardar) as chamadas demências, grupo de doenças que inclui o Alzheimer.',
        '',
        'Segundo novos estudos realizados por pesquisadores dos Estados Unidos e da Suécia, um simples exame de sangue pode medir uma proteína chamada p-tau217, e prever a doença até 20 anos antes.',
        'O diagnóstico é baseado em uma avaliação clínica, com testes cognitivos e avaliação de imagem do sistema nervoso central. A união das manifestações clínicas do paciente, do que ele e seus familiares levam até o médico, a resultados de exames complementares permite uma conclusão diagnóstica e de um tratamento abrangente.',
        'O tratamento para o Alzheimer é feito para controlar os sintomas e retardar o agravamento da degeneração cerebral provocada pela doença e inclui o uso de remédios. Além do uso de remédios, é importante fazer terapias que melhoram a independência e o raciocínio.',
    ],
    [ // MARÇO LILÁS
        'Março Lilás',
        'Prevenção ao Câncer de Colo de Útero',
        'Inicia-se a partir de um tumor que se desenvolve por alterações no colo do útero, que se localiza no fundo da vagina. Essas alterações são lesões precursoras, elas são totalmente curáveis na maioria das vezes e, se não tratadas, podem, após muitos anos, se transformar em câncer.',
        'O Instituto Nacional de Câncer (INCA) estima que para cada ano do triênio 2020/2022, sejam diagnosticados 16.590 novos casos de câncer de colo do útero no Brasil, com um risco estimado de 15,43 casos a cada 100 mil mulheres, ocupando a terceira posição.',
        'Além de aspectos relacionados à própria infecção pelo HPV, o tabagismo, a iniciação sexual precoce, a multiplicidade de parceiros sexuais, a multiparidade e o uso de contraceptivos orais são considerados fatores de risco para o desenvolvimento de câncer do colo do útero.',
        'A prevenção primária do câncer do colo do útero está relacionada à diminuição do risco de contágio pelo papilomavírus humano (HPV) com o uso de preservativos (camisinha) durante a relação sexual com penetração. A principal forma de prevenção, entretanto, é a vacina contra o HPV em conjunto com o exame preventivo (Papanicolaou).',
        '',
        'A melhor forma de diagnosticar o câncer de colo do útero precocemente é fazer exames de Papanicolau periódicos, que podem ser combinados com o teste para HPV.',
        'O diagnóstico das lesões pré-cancerosas e cancerosas é feito pelo exame de Papanicolau, pela colposcopia - que permite a visualização do colo do útero e da vagina com lentes de aumento - e pela biópsia do tecido do colo do útero.',
        'A decisão por um tipo de tratamento leva em conta a idade da paciente, estado de saúde geral da paciente e suas preferências pessoais. As principais opções de tratamento incluem cirurgia, radioterapia, quimioterapia, terapia alvo e imunoterapia, que podem ser realizadas isoladamente ou em combinação, dependendo do estágio da doença.',
    ],
    [ // ABRIL AZUL
        'Abril Azul',
        'Conscientização sobre o Autismo',
        'O autismo ou Transtorno do Espectro Autista (TEA) se refere a uma série de condições caracterizadas por algum grau de comprometimento no comportamento social, na comunicação e na linguagem.',
        'A Organização Mundial da Saúde (OMS) estima que há 70 milhões de pessoas com autismo em todo o mundo, sendo 2 milhões somente no Brasil. Estima-se que uma em cada 88 crianças apresenta traços de autismo, com prevalência cinco vezes maior em meninos.',
        'Diversos fatores como a genética e outras anomalias podem estar relacionados ao surgimento do autismo, no entanto não há causas específicas ligadas ao transtorno. Porém o TEA pode também aparecer de forma secundária, aliado a outras anomalias cromossômicas como a síndrome de Down ou de Turner, Síndromes genéticas como Rett, Angelman, a Esclerose tuberosa, X frágil, entre outras.',
        '//',
        '',
        'A detecção precoce acontece nos primeiros anos de vida, sendo os principais sintomas dificuldade no contato visual, atraso na fala e falta de resposta a chamados.',
        'O diagnóstico do autismo é essencialmente clínico, realizado por meio de observação direta do comportamento do paciente e de uma entrevista com os pais ou cuidadores.',
        'Não há cura para o autismo, visto que não é uma doença. Remédios para lidar com ele só são prescritos na presença de agressividade e de outras doenças paralelas, como depressão. O tratamento deve ser multidisciplinar, englobando médicos, fonoaudiólogos, fisioterapeutas, psicólogos e pedagogos.',
    ],
    [ // MAIO VERMELHO
        'Maio Vermelho',
        'Prevenção às Hepatites',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // JUNHO LARANJA
        'Junho Laranja',
        'Prevenção à Leucemia',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // JULHO AMARELO
        'Julho Amarelo',
        'Prevenção ao Câncer Ósseo',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // AGOSTO LARANJA
        'Agosto Laranja',
        'Prevenção à Esclerose Múltipla',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // SETEMBRO AMARELO
        'Setembro Amarelo',
        'Prevenção ao Suicídio',
        'Suicídio é o ato de causar a própria morte de forma intencional. Esta dor da alma pode ser real ou ser a consequência de uma crise de natureza afetiva, de uma conturbação mental, como, por exemplo, a psicose no seu grau mais agudo, ou de uma depressão com sintomas delirantes.',
        'Cerca de 800 mil pessoas morrem por suicídio todos os anos. Para cada suicídio, há muito mais pessoas que tentam o suicídio a cada ano. O suicídio é a segunda principal causa de morte entre jovens com idade entre 15 e 29 anos. 79% dos suicídios no mundo ocorrem em países de baixa e média renda.',
        'Pode levar o indivíduo a realizar tal ato fatores como o abuso de álcool, cigarro, histórico de suicídio entre familiares, transtornos de imagem corporal, maus-tratos na infância, violência na comunidade, desordens de humor; relacionamento familiar ruim, estresse pós-traumático, e/ou desemprego.',
        'Controlar o estresse, repousar o suficiente e desenvolver o suporte familiar, criação de leis que dificultem o acesso a armas de fogo e a promoção de campanhas que acabem com os tabus sobre depressão, esquizofrenia e afins.',
        '',
        'A detecção precoce pode ser feita analisando o bem estar da pessoa, observando comportamentos suicidas e também comportamentos depressivos.',
        'Seu médico pode fazer um exame físico, testes e questionamentos aprofundados sobre sua saúde mental e física para ajudar a determinar o que pode estar causando seu pensamento suicida e determinar o melhor tratamento. As avaliações podem incluir: Condições de saúde mental, condições de saúde física, uso indevido de álcool e drogas e medicamentos.',
        'O primeiro passo do tratamento urgente nos casos de ideação suicida é identificar a potencialidade do risco à vida, analisando questões referentes à tentativa de suicídio e aos seus motivos. Outro aspecto do tratamento é a abordagem de problemas de saúde mental relacionados à ideação suicida, assim como o tratamento clínico das possíveis lesões resultantes da tentativa de suicídio.',
    ],
    [ // OUTUBRO ROSA
        'Outubro Rosa',
        'Prevenção ao Câncer de Mama',
        '',
        '',
        'A idade é um dos principais fatores de risco para a doença (de quatro em cada cinco casos ocorrem após os 50 anos), o sedentarismo, o consumo de bebida alcoólica, histórico familiar de câncer de ovário e mama, primeira menstruação antes de 12 anos, não ter tido filhos, menopausa após os 55 anos, uso de contraceptivos hormonais (estrogênio-progesterona) e/ou primeira gravidez após os 30 anos.',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // NOVEMBRO AZUL
        'Novembro Azul',
        'Prevenção ao Câncer de Próstata',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ],
    [ // DEZEMBRO VERMELHO
        'Dezembro Vermelho',
        'Prevenção à AIDS',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
    ]
]